services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    restart: always
    networks:
      - fortinet_net
    secrets:
      - fortigate_api_token
      - fortigate_password
    volumes:
      - ./app/certs:/app/certs
    environment:
      - FORTIGATE_API_TOKEN_FILE=/run/secrets/fortigate_api_token
      - FORTIGATE_CERT_PATH=/app/certs/fortigate.pem
      - FORTIGATE_HOST=https://192.168.0.254
      - FORTIGATE_USERNAME=admin
      - FORTIGATE_PASSWORD_FILE=/run/secrets/fortigate_password
      - FORTIGATE_VERIFY_SSL=false
      - LOG_LEVEL=DEBUG
      - FORTISWITCH_HOST=192.168.0.253
      - FORTISWITCH_USERNAME=admin
      - FORTISWITCH_PASSWORD_FILE=/run/secrets/fortiswitch_password

  wan_monitor:
    build:
      context: .
      dockerfile: Dockerfile.wan_monitor
    restart: always
    networks:
      - fortinet_net
    environment:
      - FORTIGATE_HOST=https://192.168.0.254
      - FORTIGATE_API_TOKEN_FILE=/run/secrets/fortigate_api_token

secrets:
  fortigate_api_token:
    file: ./secrets/fortigate_api_token.txt
  fortigate_password:
    file: ./secrets/fortigate_password.txt
  fortiswitch_password:
    file: ./secrets/fortiswitch_password.txt

networks:
  fortinet_net:
    driver: bridge